	.align 2
voicegroup030::
	voice_directsound 60, 0, DirectSoundWaveData_mall_1, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_outside, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_mourning_dove, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_ambience_stairs, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_wall_hit_reverb, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_rolling, 8, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_rolling_reverb, 8, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_giant_catch, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_giant_battle_1, 255, 0, 255, 0
